/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aplikasiperhitungandiskon;

/**
 *
 * @author USER
 */
public class PerhitunganDiskon extends javax.swing.JPanel {

    /**
     * Creates new form PerhitunganDiskon
     */
    public PerhitunganDiskon() {
        initComponents();
        
         jComboBox2.removeAllItems();
    jComboBox2.addItem("5%");
    jComboBox2.addItem("10%");
    jComboBox2.addItem("15%");
    jComboBox2.addItem("20%");
    jComboBox2.addItem("25%");

    // Set slider 0-100
    jSlider1.setMinimum(0);
    jSlider1.setMaximum(100);
    jSlider1.setMajorTickSpacing(25);
    jSlider1.setPaintTicks(true);
    jSlider1.setPaintLabels(true);

    // Non-editable untuk hasil
    jTextField4.setEditable(false);
    jTextField5.setEditable(false);
    jTextArea1.setEditable(false);

    // Listener tombol
    jButton1.addActionListener(e -> hitungDiskon());
    jButton2.addActionListener(e -> resetForm());
    jButton3.addActionListener(e ->{
    int pilihan = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Apakah Anda yakin ingin keluar dari aplikasi?",
        "Konfirmasi Keluar",
        javax.swing.JOptionPane.YES_NO_OPTION,
        javax.swing.JOptionPane.QUESTION_MESSAGE
    );

    if (pilihan == javax.swing.JOptionPane.YES_OPTION) {
        System.exit(0);
    }
});

    // Sinkronisasi slider dan combo box
    jSlider1.addChangeListener(e -> {
        int val = jSlider1.getValue();
        jComboBox2.setSelectedItem(val + "%");
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jSlider1 = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Penghitung diskon");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel2.setText("Harga Asli:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel3.setText("Kode Kupon:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 20));

        jLabel4.setText("Harga Akhir:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel5.setText("Persentase Diskon:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 160, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 160, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 160, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 90, -1));
        add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jButton1.setText("Hitung");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        jButton2.setText("Reset");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        jButton3.setText("Keluar");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jScrollPane2.setViewportView(jTextPane1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 160, -1));

        jLabel6.setText("Penghematan:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
// ======== LOGIKA PROGRAM DISKON ==========
private void hitungDiskon() {
    try {
        // Ambil harga asli
        double hargaAsli = Double.parseDouble(jTextField2.getText());

        // Ambil diskon dari ComboBox (tanpa tanda %)
        String diskonStr = (String) jComboBox2.getSelectedItem();
        int diskon = Integer.parseInt(diskonStr.replace("%", ""));

        // Cek kode kupon (opsional)
        String kodeKupon = jTextField3.getText().trim();
        int bonusDiskon = 0;
        if (kodeKupon.equalsIgnoreCase("HEMAT10")) {
            bonusDiskon = 10;
        } else if (!kodeKupon.isEmpty() && !kodeKupon.equalsIgnoreCase("HEMAT10")) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Kode kupon tidak valid! Diskon tambahan tidak diterapkan.");
        }

        // Total diskon
        int totalDiskon = diskon + bonusDiskon;
        if (totalDiskon > 100) totalDiskon = 100;

        // Hitung harga akhir dan penghematan
        double jumlahDiskon = hargaAsli * totalDiskon / 100;
        double hargaAkhir = hargaAsli - jumlahDiskon;

        // Tampilkan hasil
        jTextField4.setText(String.format("Rp %.2f", hargaAkhir));
        jTextField5.setText(String.format("Rp %.2f", jumlahDiskon));

        // Tambah ke riwayat
        jTextArea1.append(
            "Harga Asli: Rp " + hargaAsli +
            "\nDiskon: " + totalDiskon + "%" +
            "\nHarga Akhir: Rp " + hargaAkhir +
            "\nPenghematan: Rp " + jumlahDiskon +
            "\n----------------------------\n"
        );

    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Input harga tidak valid! Masukkan angka saja.", 
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}

private void resetForm() {
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField4.setText("");
    jTextField5.setText("");
    jComboBox2.setSelectedIndex(0);
    jSlider1.setValue(0);
    jTextArea1.setText("");
}

}
